### ISSUE TITLE
Year is a few hundred years off

### ISSUE THREAD

**Issue by hammond-of-texas** [Mihonarium/RedditBot#14]
See here: https://www.reddit.com/r/TikTokCringe/comments/v9ts0n/thats_it_you_cant_top_that/ic0kihf/

`Released on 2500-12-31`

**Comment by pauljones0** [comment]
This appears to be returning a default? max value, as the actual song was released on Nov 4, 2008. I haven't looked into this more, but hopefully, this helps whoever looks at this next.

**Comment by Mihonarium** [comment]
Thanks. That was a metadata issue, [now fixed](https://www.reddit.com/r/TikTokCringe/comments/v9ts0n/comment/im8rne7/context=3).
